### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by DominicvdBroek** [KelvinTegelaar/CIPP#1215]
Goedemorgen Kevin,

Als je net Ofboarding wil doen en je klikt alles aan dan krijg je deze foutmelding:

<html>
<body>
<div class="col-md-6" style="box-sizing: border-box; flex: 0 0 auto; margin-top: var(--cui-gutter-y); max-width: 100%; padding-left: calc(var(--cui-gutter-x)*0.5); padding-right: calc(var(--cui-gutter-x)*0.5); width: 438px; color: rgb(46, 54, 58); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, roboto, &quot;Helvetica Neue&quot;, arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">An error has appeared while trying to load your data. For troubleshooting, the error information can be found in the table below.<br style="box-sizing: border-box;"><br style="box-sizing: border-box;">This type of error is usually indicative an application issue. To troubleshoot this issue check if your API is running and reachable, or use below error to troubleshoot</div><br style="box-sizing: border-box; flex-shrink: 0; margin-top: var(--cui-gutter-y); max-width: 100%; padding-left: calc(var(--cui-gutter-x)*0.5); padding-right: calc(var(--cui-gutter-x)*0.5); width: 100%; color: rgb(46, 54, 58); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, roboto, &quot;Helvetica Neue&quot;, arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="box-sizing: border-box; flex-shrink: 0; margin-top: var(--cui-gutter-y); max-width: 100%; padding-left: calc(var(--cui-gutter-x)*0.5); padding-right: calc(var(--cui-gutter-x)*0.5); width: 100%; color: rgb(46, 54, 58); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, roboto, &quot;Helvetica Neue&quot;, arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="row" style="box-sizing: border-box; --cui-gutter-x:1.5rem; --cui-gutter-y:0; display: flex; flex-wrap: wrap; margin-left: calc(var(--cui-gutter-x)*-0.5); margin-right: calc(var(--cui-gutter-x)*-0.5); margin-top: var(--cui-gutter-y); flex-shrink: 0; max-width: 100%; padding-left: calc(var(--cui-gutter-x)*0.5); padding-right: calc(var(--cui-gutter-x)*0.5); width: 876px; color: rgb(46, 54, 58); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, roboto, &quot;Helvetica Neue&quot;, arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="col" style="box-sizing: border-box; flex: 1 0 0%; margin-top: var(--cui-gutter-y); max-width: 100%; padding-left: calc(var(--cui-gutter-x)*0.5); padding-right: calc(var(--cui-gutter-x)*0.5); width: 852px;">

Error | Error Location
-- | --
Cannot read properties of undefined (reading 'map') | TypeError: Cannot read properties of undefined (reading 'map') at s.default (https://cipp.open-ict.nl/static/js/509.8c3b7c2b.chunk.js:1:11314) at oo (https://cipp.open-ict.nl/static/js/main.35737641.js:2:2120566) at Ho (https://cipp.open-ict.nl/static/js/main.35737641.js:2:2130133) at $s (https://cipp.open-ict.nl/static/js/main.35737641.js:2:2173857) at xl (https://cipp.open-ict.nl/static/js/main.35737641.js:2:2160107) at Rl (https://cipp.open-ict.nl/static/js/main.35737641.js:2:2160035) at wl (https://cipp.open-ict.nl/static/js/main.35737641.js:2:2159898) at vl (https://cipp.open-ict.nl/static/js/main.35737641.js:2:2156864) at https://cipp.open-ict.nl/static/js/main.35737641.js:2:2106358 at t.unstable_runWithPriority (https://cipp.open-ict.nl/static/js/main.35737641.js:2:2321374)

</div></div>
</body>
</html>

Overigens als je de net gecreerde users weer aanklikt als voorbeeld Dominic < null > , en in stap 4 zie je de UPN niet meer
![OffboardingUser](https://user-images.githubusercontent.com/117977775/201301097-3138a7e1-1ff7-4e60-afb7-af3ffb59b4fd.jpg)

Dezelfde error komt ook als de toggle delete user aanzet.

Bedankt weer!
Mvg,
Dominic v/d Broek

**Comment by DominicvdBroek** [comment]
Already created
