### ISSUE TITLE
Error when in Alerts or Alerts Wizard - Error Location Minified React error #31;

### ISSUE THREAD

**Issue by ParzivalMonkey** [KelvinTegelaar/CIPP#2488]
### Description

When I go in to Scripted CIPP Alert then click one of the drop downs and click off it again without selecting anything it throws an error.

Steps to reproduce:

1. Go to Tenant Administration
2. Go to Alerts
3. Click Add Alert
4. Select Scripted CIPP Alert
5. Under Alert Criteria click the "Select a Command" drop down
6. Click off it again without selecting anything

```
**Error** 
-- | --
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B0%2C%201%2C%202%2C%203%2C%204%2C%205%2C%206%2C%207%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

```
**Error Location**
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B0%2C%201%2C%202%2C%203%2C%204%2C%205%2C%206%2C%207%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings. at t7 (https://cipp.XXX.xom/static/index-B_0CKRpY.js:39:57546) at _ (https://cipp.XXX.com/static/index-B_0CKRpY.js:39:62608) at Ai (https://cipp.XXX.com/static/index-B_0CKRpY.js:39:74390) at Cve (https://cipp.XXX.com/static/index-B_0CKRpY.js:39:118892) at Sve (https://cipp.XXX.com/static/index-B_0CKRpY.js:39:112868) at xwt (https://cipp.XXX.com/static/index-B_0CKRpY.js:39:112791) at m_ (https://cipp.XXX.com/static/index-B_0CKRpY.js:39:112640) at bD (https://cipp.XXX.com/static/index-B_0CKRpY.js:39:108984) at vte (https://cipp.XXX.com/static/index-B_0CKRpY.js:39:109793) at Su (https://cipp.XXX.com/static/index-B_0CKRpY.js:39:47994)
```

Happens every time on the latest CIPP and CIPP API version.

### Environment data

```PowerShell
Not-Sponsored
Front End: 5.7.0
Back End: 5.7.3
Tried Tenant Cache Clear: False (Doesnt seem to be tenant related)
Tried Token Cache Clear: False (Doesnt seem to be token related)
```

**Comment by ParzivalMonkey** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by ParzivalMonkey** [comment]
"I confirm that I have checked the documentation thoroughly and believe this to be an actual bug."

**Comment by kris6673** [comment]
@JohnDuprey fixed this in dev
