### ISSUE TITLE
BUG: Something went wrong, offboarding user

### ISSUE THREAD

**Issue by jminexa** [KelvinTegelaar/CIPP#641]
**Describe the bug**
When performing an offboarding I got a something went wrong error; however it seemed that all of the things I selected were excecuted.

**To Reproduce**

1. Go to 'offboarding wizard'
2. Select Tenant
3. Select User
4. Select, convert to shared, disable login, reset password, give 'user' access with auto mapping

in the review part, I found it odd that the user access with auto mapping did not have a checkmark. (could be another bug).

**Screenshots**
Something went wrong.
DetailsTypeError: j.data.Results.map is not a function

    at s.default (https://zealous-cliff.azurestaticapps.net/static/js/509.3d51b191.chunk.js:2:15719)
    at Suspense
    at u (https://zealous-cliff.azurestaticapps.net/static/js/main.7b17df02.js:2:2142936)
    at Suspense
    at div
    at https://zealous-cliff.azurestaticapps.net/static/js/main.7b17df02.js:2:163425
    at div
    at div
    at div
    at D (https://zealous-cliff.azurestaticapps.net/static/js/6971.6093edb7.chunk.js:1:15559)
    at le (https://zealous-cliff.azurestaticapps.net/static/js/main.7b17df02.js:2:39477)
    at f (https://zealous-cliff.azurestaticapps.net/static/js/main.7b17df02.js:2:2143562)
    at Q (https://zealous-cliff.azurestaticapps.net/static/js/main.7b17df02.js:2:35651)
    at Suspense
    at p (https://zealous-cliff.azurestaticapps.net/static/js/main.7b17df02.js:2:2142992)
    at u (https://zealous-cliff.azurestaticapps.net/static/js/main.7b17df02.js:2:2140180)
    at h
    at t (https://zealous-cliff.azurestaticapps.net/static/js/main.7b17df02.js:2:2241722)
    at u (https://zealous-cliff.azurestaticapps.net/static/js/main.7b17df02.js:2:2137334)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome
- Version 97

**Comment by KelvinTegelaar** [comment]
cannot simulate this error.
