### ISSUE TITLE
BUG: Licenses for All Tenants

### ISSUE THREAD

**Issue by DirectITServicesUK** [KelvinTegelaar/CIPP#802]
**Describe the bug**
When viewing licenses for "All Tenants", it errors out.

**To Reproduce**
1. Go to https://**THEURL**/tenant/administration/list-licenses?customerId=AllTenants

**Expected behavior**
I assume a table with license count, but I've not seen it yet.

**Screenshots**
![image](https://user-images.githubusercontent.com/100635373/156179303-5630b814-67d1-4dbc-b73c-61351cd861d7.png)

**Desktop (please complete the following information):**

- OS: Win 11
- Browser - Edge
- Version  98.0.1108.62

**Additional context**
Error log on screen
`
```
Something went wrong.
DetailsTypeError: t.filter is not a function

    at I (https://XXXXXXXXXX/static/js/main.338cadf0.js:2:50854)
    at D (https://XXXXXXXXXX/static/js/main.338cadf0.js:2:53600)
    at div
    at https://XXXXXXXXXX/static/js/main.338cadf0.js:2:165520
    at div
    at https://XXXXXXXXXX/static/js/main.338cadf0.js:2:165144
    at div
    at f (https://XXXXXXXXXX/static/js/main.338cadf0.js:2:8268)
    at m (https://XXXXXXXXXX/static/js/main.338cadf0.js:2:9435)
    at t.default (https://XXXXXXXXXX/static/js/6465.fb189c85.chunk.js:1:606)
    at Suspense
    at u (https://XXXXXXXXXX/static/js/main.338cadf0.js:2:2301297)
    at Suspense
    at div
    at https://XXXXXXXXXX/static/js/main.338cadf0.js:2:204167
    at div
    at div
    at div
    at M (https://XXXXXXXXXX/static/js/433.93ddb928.chunk.js:1:6565)
    at le (https://XXXXXXXXXX/static/js/main.338cadf0.js:2:79811)
    at f (https://XXXXXXXXXX/static/js/main.338cadf0.js:2:2301923)
    at Q (https://XXXXXXXXXX/static/js/main.338cadf0.js:2:75985)
    at Suspense
    at p (https://XXXXXXXXXX/static/js/main.338cadf0.js:2:2301353)
    at u (https://XXXXXXXXXX/static/js/main.338cadf0.js:2:2298541)
    at g
    at t (https://XXXXXXXXXX/static/js/main.338cadf0.js:2:2406242)
    at u (https://XXXXXXXXXX/static/js/main.338cadf0.js:2:2295695)
````

**Comment by homotechsual** [comment]
I can't reproduce this on the current `dev` branch - please wait until the next release and test that if you can unless you're able to test the dev branch yourself using instructions in the docs https://cipp.app/docs/dev
