### ISSUE TITLE
BUG: Individual Domain Checker Returns Error if Entered Data Is Not a Domain Name

### ISSUE THREAD

**Issue by cwhitehbllp** [KelvinTegelaar/CIPP#871]
If data entered in the individual domain name checker is not a domain name and includes special characters, the error page below is displayed.
Something went wrong.
DetailsError: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BResults%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    at strong
    at div
    at div
    at https://cipp.hbcg.com/static/js/main.4082deb7.js:2:248642
    at div
    at t (https://cipp.hbcg.com/static/js/main.4082deb7.js:2:152300)
    at https://cipp.hbcg.com/static/js/main.4082deb7.js:2:247151
    at Re (https://cipp.hbcg.com/static/js/main.4082deb7.js:2:87272)
    at div
    at https://cipp.hbcg.com/static/js/main.4082deb7.js:2:249622
    at xe (https://cipp.hbcg.com/static/js/main.4082deb7.js:2:88036)
    at div
    at M (https://cipp.hbcg.com/static/js/433.93ddb928.chunk.js:1:6565)
    at le (https://cipp.hbcg.com/static/js/main.4082deb7.js:2:82090)
    at f (https://cipp.hbcg.com/static/js/main.4082deb7.js:2:2343216)
    at Q (https://cipp.hbcg.com/static/js/main.4082deb7.js:2:78264)
    at Suspense
    at p (https://cipp.hbcg.com/static/js/main.4082deb7.js:2:2342646)
    at u (https://cipp.hbcg.com/static/js/main.4082deb7.js:2:2339834)
    at _
    at t (https://cipp.hbcg.com/static/js/main.4082deb7.js:2:2447798)
    at u (https://cipp.hbcg.com/static/js/main.4082deb7.js:2:2336988)

**Comment by Complete-Network** [comment]
I would like to work on this please!

**Comment by johnduprey** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
Fixed in dev.
