### ISSUE TITLE
Single Tenant Access Check Fails: t.filter is not a function

### ISSUE THREAD

**Issue by jbbehar** [KelvinTegelaar/CIPP#965]
When performing a tenant access check on a specific tenant, by itself, I get the error t.filter is not a function.

If I perform the same test with two tenants selected, it passes for both, although the one that failed originally doesn't ever show an exchange result

I tried with multiple admin accounts to be sure it's not a guest account presence in Exchange causing the issue but this is not the case. I can 100% reproduce this problem with a specific tenant. 

`Something went wrong.
DetailsTypeError: t.filter is not a function

    at I (https://m.relentless.net/static/js/main.68e5ef42.js:2:13116)
    at div
    at https://m.relentless.net/static/js/main.68e5ef42.js:2:142694
    at div
    at https://m.relentless.net/static/js/main.68e5ef42.js:2:142318
    at div
    at https://m.relentless.net/static/js/main.68e5ef42.js:2:180259
    at div
    at https://m.relentless.net/static/js/main.68e5ef42.js:2:181806
    at div
    at C (https://m.relentless.net/static/js/8666.2068786d.chunk.js:1:7086)
    at div
    at t (https://m.relentless.net/static/js/main.68e5ef42.js:2:125732)
    at https://m.relentless.net/static/js/main.68e5ef42.js:2:220038
    at div
    at https://m.relentless.net/static/js/main.68e5ef42.js:2:219774
    at div
    at https://m.relentless.net/static/js/main.68e5ef42.js:2:142694
    at div
    at r (https://m.relentless.net/static/js/3423.0a8e7fbc.chunk.js:1:245)
    at g (https://m.relentless.net/static/js/8666.2068786d.chunk.js:1:5989)
    at Suspense
    at oe (https://m.relentless.net/static/js/main.68e5ef42.js:2:41802)
    at u (https://m.relentless.net/static/js/main.68e5ef42.js:2:2204521)
    at Suspense
    at div
    at https://m.relentless.net/static/js/main.68e5ef42.js:2:181341
    at div
    at div
    at div
    at M (https://m.relentless.net/static/js/6971.dd17bab9.chunk.js:1:6566)
    at oe (https://m.relentless.net/static/js/main.68e5ef42.js:2:41802)
    at f (https://m.relentless.net/static/js/main.68e5ef42.js:2:2205147)
    at V (https://m.relentless.net/static/js/main.68e5ef42.js:2:37980)
    at Suspense
    at p (https://m.relentless.net/static/js/main.68e5ef42.js:2:2204577)
    at u (https://m.relentless.net/static/js/main.68e5ef42.js:2:2201765)
    at b
    at t (https://m.relentless.net/static/js/main.68e5ef42.js:2:2371607)
    at u (https://m.relentless.net/static/js/main.68e5ef42.js:2:2198919)`

**Comment by KelvinTegelaar** [comment]
Fixed in dev. :)

**Comment by coolnetworks** [comment]
I am still seeing this on my sponsored instance

**Comment by KelvinTegelaar** [comment]
in the latest version we've performed another fix for this, expected to release Monday. :)
